version: '3'
services:
  app-instance1:
    image: your-app-image
    ports:
      - "8080:80"
    container_name: app-instance1

  app-instance2:
    image: your-app-image
    ports:
      - "8081:80"
    container_name: app-instance2

  nginx-lb:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /path/to/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx-lb

