version: '3'
services:
  app-instance1:
    image: your-app-image # create a image with reqired contents and change the as per wish
    networks:
      - myapp-network # give network name as per wish and change in the file
    container_name: app-instance1  # give container name as per ur wish

  app-instance2:
    image: your-app-image # create a image with reqired contents and change the as per wish
    networks:
      - myapp-network # give network name as per wish and change in the file
    container_name: app-instance2  # give container name as per ur wish

  nginx-lb:
    image: nginx
    networks:
      - myapp-network
    ports:
      - "80:80"
    volumes:
      - /path/to/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx-lb

networks:
  myapp-network:
